### PR TITLE
Kelly updates.

### PR DESCRIPTION
**Pull request by KoreabooCE**
Kelly if you are a real dev for Monyx please respond here and tell us when we will get updates on the website. Thank you.

### CODE REVIEW

**Comment by cryptowhiteboard** [comment]
Also please resolve btc not showing up on dashboard so we can advise people that its ok to deposit btc again

**Comment by Palkkari** [comment]
@monyxcoin 
We have supported you all this time, time to give something back, atleast an update.

**Comment by CryptoReece** [comment]
BTC Deposit issue still not fixed. COME ON MONYX NO UPDATES, BTC DISSAPERING ON DEPOSIT I AM HEAVILY INVESTED IN YOU PLATFORM THE LEAST YOU COULD DO IS UPDATE US ON YOUR PROGRESS YOUR NOT GIVING US MUCH CONFIDENCE ABOUT THE PLATFORM GIVE US AN UPDATE AND YOUR LOYAL INVESTORS WILL BE HAPPY AND WITH BRING IN NEW INVESTORS AND POSSIBLY BUMP THE PRICE!!!!

**Comment by oanh1987son** [comment]
I was deposited 2 days ago but no show up on my transaction history and i didn't receive Btc.When i receive Btc in my wallet

**Comment by cryptowhiteboard** [comment]
The sites back up but i still dont have my btc and its now sitting in the hot wallet. Please fix

**Comment by GTHB4KliF** [comment]
Also still No BTC in my Wallet. (transfer BTC to monyx 16th of march.)
21th March 22:31 CE Could not log in. White screen "page expired ..."
22nd March 20:57 CET Could not log in. White screen "page expired ..."

**Comment by chass3768** [comment]
Can any of you log into Monyx at this time?

**Comment by crypto1512** [comment]
No, I am also facing same problems with monyx. And the monyx team is sleeping because its almost a month passing from last update(news)....

**Comment by crypto1512** [comment]
No, I am also facing same problems with monyx. And the monyx team is sleeping because its almost a month passing from last update(news)....

**Comment by chass3768** [comment]
@monyxcoin  fix the log in issue. I keep getting the page has timed out please refresh and try again error. What a joke this has become.

**Comment by GTHB4KliF** [comment]
Now 20:53 CET not able to log in !!

**Comment by cryptowhiteboard** [comment]
https://youtu.be/Ax9gBhPKtZ0 
a link for the most current monyx update guys, hang in there good things are on the way soon

**Comment by emreboy** [comment]
Thieves

**Comment by crypto1512** [comment]
Hello, monyx team, where are you people?
Come and gives us updates....

**Comment by crypto1512** [comment]
What's happening in monyx and monyx team whats doing? This situation is very non serious attitude. Monyx is talking a lot and practically doing nothing, even a single word couldn't came out from their mouth...

**Pull request closed without merging**
